package com.TrackFile.app.domain.enums;

public enum TipoAlerta {
    DOCUMENTO_VENCIMIENTO,
    DOCUMENTO_VENCIDO,
    MANTENIMIENTO_PROGRAMADO,
    MANTENIMIENTO_SUGERIDO,
    MANTENIMIENTO_ACTUALIZADO,
    MANTENIMIENTO_PROXIMO,
    SOLICITUD_CREADA,
    SOLICITUD_ACTUALIZADA,
    VEHICULO_SIN_CONDUCTOR,
    SISTEMA
}